[build]
  publish = "public"
  functions = "func"
  command = "node --unhandled-rejections=strict build.js"

[build.environment]
  AWS_LAMBDA_JS_RUNTIME = "nodejs14.x"

[build.processing]
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

[functions]
  node_bundler = "esbuild"

[template.environment]
  DISCORD_CLIENT_ID = "Your Discord App's client ID"
  DISCORD_CLIENT_SECRET = "Your Discord App's client secret"
  DISCORD_BOT_TOKEN = "Your Discord Bot Token"
  GUILD_ID = "ID of the guild this deployment targets"
  APPEALS_CHANNEL = "ID of the channel used for appeal form submission"
  JWT_SECRET = "JSON Web Token secret, mash keyboard plz"